ThAmCo.Customer.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ThAmCo.Customer.Services.Orders;

namespace ThAmCo.Customer.Web.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrdersService _orders;

        public OrdersController(IOrdersService orders)
        {
            _orders = orders;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (User == null)
            {
                return BadRequest();
            }

            string suid = User.Claims.FirstOrDefault(c => c.Type == "sub").Value;

            return View(await _orders.GetOrdersAsync(suid));
        }
    }
}

ThAmCo.Customer.Web/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ThAmCo.Customer.Models;
using ThAmCo.Customer.Services.Orders;
using ThAmCo.Customer.Services.Products;
using ThAmCo.Customer.Services.Reviews;

namespace ThAmCo.Customer.Web.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IProductsService _products;
        private readonly IOrdersService _orders;
        private readonly IReviewsService _reviews;

        public ReviewsController(IProductsService products, IOrdersService orders, IReviewsService reviews)
        {
            _products = products;
            _orders = orders;
            _reviews = reviews;
        }

        private async Task<bool> checkCanReview(int productId)
        {
            string suid = User.Claims.FirstOrDefault(c => c.Type == "sub").Value;
            if (suid == null)
            {
                return false;
            }

            bool hasOredered = await _orders.CustomerHasOrderedAsync(productId, suid);

            if (!hasOredered)
            {
                return false;
            }

            return true;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create(int id)
        {
            ProductDto product = await _products.GetByIDAsync(id);

            if (product == null)
            {
                return BadRequest();
            }

            if (User == null)
            {
                return BadRequest();
            }

            bool canReview = await checkCanReview(id);

            if (!canReview)
            {
                return BadRequest();
            }

            return View(new ReviewDto 
            { 
                ProductId = id
            });
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title","Description","Rating","ProductId")] ReviewDto review)
        {
            ProductDto product = await _products.GetByIDAsync(review.ProductId);

            if (product == null)
            {
                return BadRequest();
            }

            if (User == null)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                bool canReview = await checkCanReview(review.ProductId);

                if (!canReview)
                {
                    TempData["error"] = "You cannot review this product.";
                    return RedirectToAction("Details", "Products", new { @id = review.ProductId });
                }

                var created = await _reviews.CreateReview(review);

                if (created)
                {
                    return RedirectToAction("Index", "Orders");
                }
            }

            return View(review);
        }
    }
}

ThAmCo.Customer.Web/Views/Orders/Index.cshtml
@model IEnumerable<ThAmCo.Customer.Models.OrderGetDto>

@{
    ViewData["Title"] = "Orders";
}

<div class="jumbotron">
    <div class="container">
        <h1>Your Order History</h1>
    </div>
</div>

<div class="container">
    @foreach (var item in Model)
    {
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <img src="//via.placeholder.com/250" class="img-fluid">
                    </div>
                    <div class="col-md-6">
                        <h3><small>Order @Html.DisplayFor(modelItem => item.Id)</small></h3>
                        <p class="mb-0"><b>Item Price:</b> @Html.DisplayFor(modelItem => item.Price)</p>
                        <p class="mb-0"><b>Dispatched:</b> @Html.DisplayFor(modelItem => item.ViewStatus)</p>
                        <p><b>Date:</b> @Html.DisplayFor(modelItem => item.TimePlaced)</p>
                        <a class="btn btn-primary" asp-controller="Products" asp-action="Details" asp-route-id="@item.Product.Id">View the product</a>
                        <a class="btn btn-outline-dark" asp-controller="Reviews" asp-action="Create" asp-route-id="@item.Product.Id">Write a review</a>
                    </div>
                </div>
            </div>
        </div>
    }

    @if (Model.Count() == 0)
    {
        <div class="row">
            <div class="col-md-12">
                <p>You have no orders.</p>
            </div>
        </div>
    }
</div>